import { useEffect, useState } from 'react'
import { requireSupabase } from '../../lib/supabase'
type Question = { concept: string; question: string; choices: string[]; answer_index: number; explanation: string }
export function CoursePractice({ courseId }: { courseId: string }) {
  const [questions, setQuestions] = useState<Question[]>([]); const [index, setIndex] = useState(0); const [selected, setSelected] = useState<number | null>(null); const [checked, setChecked] = useState(false); const [score, setScore] = useState(0); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [weak, setWeak] = useState<string[]>([])
  // Progress is loaded once for the selected course; loadProgress only reads that course.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void loadProgress() }, [courseId])
  async function loadProgress() { const session = (await requireSupabase().auth.getSession()).data.session; if (!session) return; const api = import.meta.env.VITE_API_URL?.replace(/\/$/, '') || 'http://localhost:8000'; const response = await fetch(`${api}/courses/${courseId}/progress`, { headers: { Authorization: `Bearer ${session.access_token}` } }); if (response.ok) { const rows = await response.json(); setWeak(rows.filter((row: { last_result: boolean | null }) => row.last_result === false).map((row: { concept: string }) => row.concept)) } }
  async function generate() { setBusy(true); setError(''); try { const session = (await requireSupabase().auth.getSession()).data.session; if (!session) throw new Error('Your session expired.'); const api = import.meta.env.VITE_API_URL?.replace(/\/$/, '') || 'http://localhost:8000'; const response = await fetch(`${api}/courses/${courseId}/quiz`, { method: 'POST', headers: { Authorization: `Bearer ${session.access_token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ count: 5 }) }); const result = await response.json(); if (!response.ok) throw new Error(result.detail || 'Quiz generation failed.'); setQuestions(result.questions); setIndex(0); setScore(0); setSelected(null); setChecked(false) } catch (error) { setError(error instanceof Error ? error.message : 'Quiz generation failed.') } finally { setBusy(false) } }
  if (!questions.length) return <section className="panel empty-state"><span className="large-symbol">▤</span><h2>Practice from your course.</h2><p>Generate fresh questions from published materials and approved course guidance.</p>{weak.length > 0 && <p className="form-message">Concepts to revisit: {weak.join(', ')}</p>}{error && <p className="form-error" role="alert">{error}</p>}<button className="primary" disabled={busy} onClick={() => void generate()}>{busy ? 'Generating questions…' : 'Generate a practice quiz →'}</button></section>
  if (index >= questions.length) return <section className="panel empty-state"><span className="large-symbol">✧</span><h2>Practice complete.</h2><p>You answered {score} of {questions.length} correctly.</p><button className="primary" onClick={() => void generate()}>Generate a new quiz →</button></section>
  const question = questions[index]; const correct = selected === question.answer_index
  return <section className="panel quiz"><div className="section-heading"><span className="eyebrow">LIVE COURSE PRACTICE</span><span className="muted">Question {index + 1} of {questions.length}</span></div><progress value={index} max={questions.length}/><span className="badge developing">{question.concept}</span><h2>{question.question}</h2><fieldset disabled={checked}><legend className="sr-only">Choose an answer</legend>{question.choices.map((choice, i) => <label className={`answer ${selected === i ? 'selected' : ''} ${checked && i === question.answer_index ? 'correct' : ''}`} key={choice}><input type="radio" name="course-answer" checked={selected === i} onChange={() => setSelected(i)}/><span className="answer-letter">{String.fromCharCode(65 + i)}</span>{choice}</label>)}</fieldset>{checked && <div className={`feedback ${correct ? 'success' : ''}`}><strong>{correct ? 'Correct.' : 'Review this concept.'}</strong><p>{question.explanation}</p></div>}<div className="quiz-actions">{checked ? <button className="primary" onClick={() => { setIndex(index + 1); setSelected(null); setChecked(false) }}>{index + 1 === questions.length ? 'Finish' : 'Next question'} →</button> : <button className="primary" disabled={selected === null} onClick={async () => { const answer = selected === question.answer_index; setChecked(true); setScore(score + Number(answer)); try { const session = (await requireSupabase().auth.getSession()).data.session; const api = import.meta.env.VITE_API_URL?.replace(/\/$/, '') || 'http://localhost:8000'; await fetch(`${api}/courses/${courseId}/progress`, { method: 'POST', headers: { Authorization: `Bearer ${session?.access_token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ concept: question.concept, correct: answer }) }); await loadProgress() } catch { /* feedback remains usable if the progress service is temporarily unavailable */ } }}>Check answer →</button>}</div></section>
}
